### PR TITLE
Admin objects

### PR DESCRIPTION
**Pull request by wtrocki**
WIP for admin system. Still in progress.

FYI needed to disable map as there was no typing involved. 
I think we do need react package considering the amount of hacks I needed to put into this and it still did not compile for me

### CODE REVIEW

**Comment by wtrocki** [comment]
Merging to fix some of the issues

**Comment by machi1990** [comment]
Ah strange, I remember adding them for the client side - https://github.com/aerogear/OpenVolunteerPlatform/pull/26/files#diff-c33b8440bb4caa4fc79af0bf097ef5a9R74. Did you do `yarn` after pulling in the Map changes?

**Comment by machi1990** [comment]
Ah also I should have added them on the `admin` app too.

**Comment by wtrocki** [comment]
Yep. it was on me. I did not notice that client had this types

**Pull request merged**
